application: mylittledrawing
version: 1
runtime: go
api_version: 2

handlers:
- url: /static
  static_dir: static
- url: /_ah/channel/.*
  script: _go_app
- url: /.*
  script: _go_app
  login: required

inbound_services:
- channel_presence
