application: mylittledrawing
version: 2
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
- url: /_ah/channel/.*
  script: _go_app
- url: /.*
  script: _go_app
  login: required

inbound_services:
- channel_presence
